.obj .mtl export
Bdtrotte/3D-Map-Gen pull request #62
Opened 2018-03-06 01:09 UTC by wswlymf

2018-03-06 06:19 UTC, timoffex reviewed
First pass -- everything looks good and compiles! I can't figure out how to get Preview (on Mac) to actually show the textures when I export though.

2018-03-06 06:19 UTC, timoffex commented on WallsAndHoles/simpletexturedobject.cpp
> +    return QString(QCryptographicHash::hash(feature.toUtf8(),QCryptographicHash::Md5).toHex());
Interesting solution!

2018-03-06 06:19 UTC, timoffex commented on WallsAndHoles/objtools.h
> +*/
Is this necessary to keep, or did you mean to remove it?

2018-03-06 21:26 UTC, Bdtrotte commented on WallsAndHoles/objtools.h
> +    ~OBJModel(){
Not required

2018-03-06 21:26 UTC, Bdtrotte commented on WallsAndHoles/teapot.obj
> +mtllib spider.mtl
Lets remove

2018-03-07 01:03 UTC, Bdtrotte requested changes

2018-03-07 01:03 UTC, Bdtrotte commented on WallsAndHoles/simpletexturedobject.cpp
> +    return QString(QCryptographicHash::hash(feature.toUtf8(),QCryptographicHash::Md5).toHex());
This needs to be the name the user sets... If the fact that the user could have different materials with the same name is a problem, then handle that, and add "_id" to the end of the name. Currently, when importing to something like unity, you end up with a bunch of materials whos name makes no sense...

2018-03-07 20:40 UTC, merged